### ISSUE TITLE
Clarify test procedures and questions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-axsdb-web#60]
Example Procedure:
1. Enter a value in the name field
2. Click the "Send name" button, making sure the name field is empty.
3. Access a page with mandatory form fields in a user agent that supports the Accessible Rich Internet Applications specification.
4. Check that the user agent notifies of the missing information.
5. Click the "Send name" button.

Test result question:
Did the user agent prevent submitting on step 3 and allow it on step 5?

**Comment by sharronrush** [comment]
@yatil @WilcoFiers What is status of this - can we close it?
